In [167]:
import os
import numpy as np 
import pandas as pd

In [168]:
os.getcwd()

'C:\\Users\\jhard\\Downloads'

In [169]:
os.chdir('C:\\Users\\jhard\\Downloads')

In [170]:
messy_data = pd.read_csv('dirty_financial_transactions.csv')

In [171]:
messy_data.head()

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status
0,T0001,2024-08-02,C2205,Headphones,-5.0,$420.21,pay pal,NaN
1,T0002,2020-02-10,C3156,Coffee,469.0,-445.34202525395585,creditcard,Pending
2,T0003,2025-02-30,C2919,Tablet,-4.0,810.9930123946459,credit card,completed
3,T0004,2020-08-17,C3009,Tab,-7.0,868.6083413217348,PayPal,Pending
4,T0005,2025-02-30,C3488,Coffee Machine,-10.0,-763.1224490039416,PayPal,completed

Problems in this Dataset

- null values present
- duplicates rows are present
- Many Columns Name for one Category
- Negative Values in Quantity
- Negative Values in Price
- Wrong Data Types for Many Columns

In [172]:
print('total no of rows in this Dataset -', messy_data.shape[0])

total no of rows in this Dataset - 100000

In [173]:
print('total no of Columns in this Dataset -', messy_data.shape[1])

total no of Columns in this Dataset - 8

In [174]:
messy_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Transaction_ID      94982 non-null   object
 1   Transaction_Date    95120 non-null   object
 2   Customer_ID         95122 non-null   object
 3   Product_Name        100000 non-null  object
 4   Quantity            94981 non-null   float64
 5   Price               66503 non-null   object
 6   Payment_Method      100000 non-null  object
 7   Transaction_Status  83321 non-null   object
dtypes: float64(1), object(7)
memory usage: 6.1+ MB

Price, Quantity and Transaction Data has Wrong Data Types

Identity How many Null Values are there in Each Column

Percentage of Null Values in Each columns

In [175]:
messy_data.isnull().sum()/len(messy_data)*100

Transaction_ID         5.018
Transaction_Date       4.880
Customer_ID            4.878
Product_Name           0.000
Quantity               5.019
Price                 33.497
Payment_Method         0.000
Transaction_Status    16.679
dtype: float64

Identify how many duplicated Rows are present in Dataset

In [176]:
print('Total No of Duplicates Rows in Dataset', messy_data[messy_data.duplicated()].shape[0])

Total No of Duplicates Rows in Dataset 994

We will drop duplicate Rows in Dataset Later

In [177]:
messy_data['Customer_ID'].value_counts()

Customer_ID
C4347    37
C2023    37
C4418    36
C876     36
C1955    35
         ..
C3782     7
C3324     7
C1635     7
C945      6
C1384     5
Name: count, Length: 5000, dtype: int64

So There are some Customers Who have Multiple rows in Dataset

So We will check that these rows are same or different

In [178]:
messy_data[messy_data['Customer_ID'] == 'C4347']

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status
538,T0539,2023-13-01,C4347,Headphones,-7.0,NaN,PayPal,completed
642,T0643,2021-04-09,C4347,Laptop,-4.0,841.2991021061262,Cash,Failed
8934,T8935,2023-01-31,C4347,Coffee Machine,8.0,$-574.76,PayPal,Pending
12693,T12694,2023-13-01,C4347,Laptop,-10.0,-446.3360641696613,credit card,Failed
13670,T13671,2023-13-01,C4347,Headphones,923.0,$998.79,Credit Card,Completed
16148,T16149,2023-13-01,C4347,Headphones,9.0,NaN,credit card,complete
19422,T19423,2024-11-29,C4347,Headphones,NaN,-721.7148471235098,PayPal,Pending
22006,T22007,2025-02-30,C4347,Laptop,943.0,-464.77374826930225,PayPal,completed
23963,T23964,2023-10-14,C4347,Tablet,-6.0,63.78126911461825,Cash,Failed
24496,T24497,2020-05-09,C4347,Coffee Machine,439.0,845.894271048739,Credit Card,NaN
28268,T28269,2022-01-28,C4347,Coffee Machine,782.0,83.78726854105909,Cash,NaN
29775,T29776,2025-02-30,C4347,Smartphone,2.0,412.74448089734557,PayPal,NaN
30568,T30569,2023-13-01,C4347,Smartphone,9.0,NaN,PayPal,Completed
31578,T31579,NaN,C4347,Laptop,203.0,630.1139645290243,Cash,completed
34666,T34667,NaN,C4347,Headphones,648.0,77.4385106949296,creditcard,complete
37024,T37025,2020-06-28,C4347,Coffee Machine,-8.0,961.4965588778634,Credit Card,NaN
42106,T42107,2022-03-26,C4347,Smartphone,4.0,108.15306848394795,pay pal,NaN
46412,T46413,NaN,C4347,Tablet,-5.0,-298.1905376994722,PayPal,completed
47691,T47692,2023-13-01,C4347,Coffee Machine,NaN,-431.8049553318426,PayPal,Pending
52498,T52499,2024-02-21,C4347,Headphones,6.0,NaN,PayPal,Pending
53033,T53034,2022-03-28,C4347,Tablet,-10.0,-500.9045764349556,pay pal,complete
56377,T56378,2025-02-30,C4347,Tablet,-7.0,-960.6096431932419,credit card,Completed
59216,T59217,2025-02-30,C4347,Smartphone,8.0,NaN,credit card,Failed
59563,T59564,2023-11-25,C4347,Smartphone,6.0,362.10089769012114,pay pal,complete
61414,T61415,2023-13-01,C4347,Coffee,-6.0,962.7559373542065,creditcard,Failed
63235,T63236,2024-03-20,C4347,Coffee Machine,7.0,285.47318990383417,creditcard,Completed
65780,T65781,2025-02-30,C4347,Tablet,2.0,-935.2469965207804,PayPal,NaN
67629,T67630,2023-13-01,C4347,Headphones,6.0,720.6573803807463,Cash,Pending
73831,T73832,2023-13-01,C4347,Headphones,895.0,NaN,PayPal,NaN
74995,T74996,2023-13-01,C4347,Smartphone,698.0,NaN,creditcard,NaN
80504,T80505,2024-05-14,C4347,Smart,-10.0,-709.8573120690774,pay pal,Pending
86570,T86571,2025-02-30,C4347,Tablet,712.0,-455.95903959626423,creditcard,complete
91072,T91073,2023-13-01,C4347,Headphones,5.0,598.8637860291242,creditcard,Failed
93861,T93862,2025-02-30,C4347,Coffee Machine,-10.0,NaN,Cash,NaN
94604,T94605,2023-13-01,C4347,Smartphone,260.0,NaN,credit card,complete
95586,T95587,2023-13-01,C4347,Coffee Machine,-4.0,-738.7641592882494,Cash,Failed
97351,T97352,2023-13-01,C4347,Headphones,789.0,-657.0273750042332,PayPal,Failed

So Each Rows is Different

Now we identity problem in Columns Name

In [179]:
for col in messy_data.columns:
  if messy_data[col].nunique() < 50:
    print(messy_data[col].value_counts())
    print('-'*50)

Product_Name
Tablet            18444
Laptop            18264
Smartphone        18257
Headphones        18107
Coffee Machine    18085
Lapt                370
Table               352
La                  347
Tabl                346
Lapto               344
Ta                  344
T                   335
Lap                 334
Tab                 330
L                   321
Smartph             234
S                   223
H                   217
He                  212
Smart               206
Head                204
Headpho             203
Smartphon           203
Headphon            203
Smartp              203
Headphone           202
Headp               201
Headph              193
Hea                 192
Sma                 191
Sm                  189
Smartpho            181
Smar                180
Coffee Ma           157
Coffee Machin       150
Coffee Machi        150
Coffee Mach         149
Coffee              149
C                   141
Coffee M            140
Cof                 137
Coffe               129
Coffee              125
Coffee Mac          123
Co                  119
Coff                114
Name: count, dtype: int64
--------------------------------------------------
Payment_Method
Credit Card    14433
creditcard     14384
pay pal        14357
PayPal         14262
Cash           14212
credit card    14198
PayPal         14154
Name: count, dtype: int64
--------------------------------------------------
Transaction_Status
Failed       16795
complete     16717
completed    16687
Pending      16595
Completed    16527
Name: count, dtype: int64
--------------------------------------------------

Here We can see different names for Same Category

In [180]:
messy_data['Price'].sort_values().unique()

# In Price Column, There is '$' sign and some null values

array(['$-100.57', '$-100.87', '$-100.96', ..., '999.9851066256931',
       '999.9876977023494', nan], shape=(65758,), dtype=object)

Till now We Focus on Identify Problems in this messy Dataset.

Now We will do Data Cleaning and Manuplation

In [181]:
# Dropping Duplicated Values

messy_data.drop_duplicates(inplace=True)

In [182]:
# Checking duplicates values again

messy_data[messy_data.duplicated()]

Empty DataFrame
Columns: [Transaction_ID, Transaction_Date, Customer_ID, Product_Name, Quantity, Price, Payment_Method, Transaction_Status]
Index: []

In [183]:
# dropping rows where customer id is null

messy_data.dropna(subset=['Customer_ID'], inplace=True)

In [184]:
messy_data.isnull().sum()/len(messy_data)*100

Transaction_ID         5.026758
Transaction_Date       4.871730
Customer_ID            0.000000
Product_Name           0.000000
Quantity               5.019326
Price                 33.468187
Payment_Method         0.000000
Transaction_Status    16.661357
dtype: float64

In [185]:
# generating transacation id for null values

# Total rows count karein
n = len(messy_data)

# Nayi IDs generate karein (T00001 format mein)
messy_data['Transaction_ID'] = [f'T{str(i+1).zfill(5)}' for i in range(n)]

In [186]:
messy_data.isnull().sum()/len(messy_data)*100

Transaction_ID         0.000000
Transaction_Date       4.871730
Customer_ID            0.000000
Product_Name           0.000000
Quantity               5.019326
Price                 33.468187
Payment_Method         0.000000
Transaction_Status    16.661357
dtype: float64

In [187]:
# changing price data types and working on null values and '$'

messy_data['Price'].str.startswith('$').value_counts()

Price
False    56416
True      6241
Name: count, dtype: int64

In [188]:
messy_data["Price"] = messy_data['Price'].str.replace('$', '', regex=False)

In [189]:
messy_data['Price'].sort_values().unique()

array(['-100.1120385623841', '-100.12379265881964', '-100.15344745799246',
       ..., '999.9851066256931', '999.9876977023494', nan],
      shape=(62550,), dtype=object)

In [190]:
messy_data['Price'] = messy_data['Price'].astype(float)

In [191]:
messy_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 94176 entries, 0 to 99998
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      94176 non-null  object
 1   Transaction_Date    89588 non-null  object
 2   Customer_ID         94176 non-null  object
 3   Product_Name        94176 non-null  object
 4   Quantity            89449 non-null  float64
 5   Price               62657 non-null  float64
 6   Payment_Method      94176 non-null  object
 7   Transaction_Status  78485 non-null  object
dtypes: float64(2), object(6)
memory usage: 6.5+ MB

In [192]:
messy_data['Price'].sort_values().unique()

array([-999.96890297, -999.94363099, -999.91582127, ...,  999.98510663,
        999.9876977 ,           nan], shape=(62550,))

In [193]:
messy_data['Price'] = messy_data['Price'].fillna(messy_data['Price'].median())

In [194]:
messy_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 94176 entries, 0 to 99998
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      94176 non-null  object
 1   Transaction_Date    89588 non-null  object
 2   Customer_ID         94176 non-null  object
 3   Product_Name        94176 non-null  object
 4   Quantity            89449 non-null  float64
 5   Price               94176 non-null  float64
 6   Payment_Method      94176 non-null  object
 7   Transaction_Status  78485 non-null  object
dtypes: float64(2), object(6)
memory usage: 6.5+ MB

In [195]:
# working in Quantity Columns

In [196]:
messy_data['Quantity'].sort_values().unique()

array([ -10.,   -9.,   -8.,   -7.,   -6.,   -5.,   -4.,   -3.,   -2.,
         -1.,    1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,
          9.,   10.,  100.,  101.,  102.,  103.,  104.,  105.,  106.,
        107.,  108.,  109.,  110.,  111.,  112.,  113.,  114.,  115.,
        116.,  117.,  118.,  119.,  120.,  121.,  122.,  123.,  124.,
        125.,  126.,  127.,  128.,  129.,  130.,  131.,  132.,  133.,
        134.,  135.,  136.,  137.,  138.,  139.,  140.,  141.,  142.,
        143.,  144.,  145.,  146.,  147.,  148.,  149.,  150.,  151.,
        152.,  153.,  154.,  155.,  156.,  157.,  158.,  159.,  160.,
        161.,  162.,  163.,  164.,  165.,  166.,  167.,  168.,  169.,
        170.,  171.,  172.,  173.,  174.,  175.,  176.,  177.,  178.,
        179.,  180.,  181.,  182.,  183.,  184.,  185.,  186.,  187.,
        188.,  189.,  190.,  191.,  192.,  193.,  194.,  195.,  196.,
        197.,  198.,  199.,  200.,  201.,  202.,  203.,  204.,  205.,
        206.,  207.,  208.,  209.,  210.,  211.,  212.,  213.,  214.,
        215.,  216.,  217.,  218.,  219.,  220.,  221.,  222.,  223.,
        224.,  225.,  226.,  227.,  228.,  229.,  230.,  231.,  232.,
        233.,  234.,  235.,  236.,  237.,  238.,  239.,  240.,  241.,
        242.,  243.,  244.,  245.,  246.,  247.,  248.,  249.,  250.,
        251.,  252.,  253.,  254.,  255.,  256.,  257.,  258.,  259.,
        260.,  261.,  262.,  263.,  264.,  265.,  266.,  267.,  268.,
        269.,  270.,  271.,  272.,  273.,  274.,  275.,  276.,  277.,
        278.,  279.,  280.,  281.,  282.,  283.,  284.,  285.,  286.,
        287.,  288.,  289.,  290.,  291.,  292.,  293.,  294.,  295.,
        296.,  297.,  298.,  299.,  300.,  301.,  302.,  303.,  304.,
        305.,  306.,  307.,  308.,  309.,  310.,  311.,  312.,  313.,
        314.,  315.,  316.,  317.,  318.,  319.,  320.,  321.,  322.,
        323.,  324.,  325.,  326.,  327.,  328.,  329.,  330.,  331.,
        332.,  333.,  334.,  335.,  336.,  337.,  338.,  339.,  340.,
        341.,  342.,  343.,  344.,  345.,  346.,  347.,  348.,  349.,
        350.,  351.,  352.,  353.,  354.,  355.,  356.,  357.,  358.,
        359.,  360.,  361.,  362.,  363.,  364.,  365.,  366.,  367.,
        368.,  369.,  370.,  371.,  372.,  373.,  374.,  375.,  376.,
        377.,  378.,  379.,  380.,  381.,  382.,  383.,  384.,  385.,
        386.,  387.,  388.,  389.,  390.,  391.,  392.,  393.,  394.,
        395.,  396.,  397.,  398.,  399.,  400.,  401.,  402.,  403.,
        404.,  405.,  406.,  407.,  408.,  409.,  410.,  411.,  412.,
        413.,  414.,  415.,  416.,  417.,  418.,  419.,  420.,  421.,
        422.,  423.,  424.,  425.,  426.,  427.,  428.,  429.,  430.,
        431.,  432.,  433.,  434.,  435.,  436.,  437.,  438.,  439.,
        440.,  441.,  442.,  443.,  444.,  445.,  446.,  447.,  448.,
        449.,  450.,  451.,  452.,  453.,  454.,  455.,  456.,  457.,
        458.,  459.,  460.,  461.,  462.,  463.,  464.,  465.,  466.,
        467.,  468.,  469.,  470.,  471.,  472.,  473.,  474.,  475.,
        476.,  477.,  478.,  479.,  480.,  481.,  482.,  483.,  484.,
        485.,  486.,  487.,  488.,  489.,  490.,  491.,  492.,  493.,
        494.,  495.,  496.,  497.,  498.,  499.,  500.,  501.,  502.,
        503.,  504.,  505.,  506.,  507.,  508.,  509.,  510.,  511.,
        512.,  513.,  514.,  515.,  516.,  517.,  518.,  519.,  520.,
        521.,  522.,  523.,  524.,  525.,  526.,  527.,  528.,  529.,
        530.,  531.,  532.,  533.,  534.,  535.,  536.,  537.,  538.,
        539.,  540.,  541.,  542.,  543.,  544.,  545.,  546.,  547.,
        548.,  549.,  550.,  551.,  552.,  553.,  554.,  555.,  556.,
        557.,  558.,  559.,  560.,  561.,  562.,  563.,  564.,  565.,
        566.,  567.,  568.,  569.,  570.,  571.,  572.,  573.,  574.,
        575.,  576.,  577.,  578.,  579.,  580.,  581.,  582.,  583.,
        584.,  585.,  586.,  587.,  588.,  589.,  590.,  591.,  592.,
        593.,  594.,  595.,  596.,  597.,  598.,  599.,  600.,  601.,
        602.,  603.,  604.,  605.,  606.,  607.,  608.,  609.,  610.,
        611.,  612.,  613.,  614.,  615.,  616.,  617.,  618.,  619.,
        620.,  621.,  622.,  623.,  624.,  625.,  626.,  627.,  628.,
        629.,  630.,  631.,  632.,  633.,  634.,  635.,  636.,  637.,
        638.,  639.,  640.,  641.,  642.,  643.,  644.,  645.,  646.,
        647.,  648.,  649.,  650.,  651.,  652.,  653.,  654.,  655.,
        656.,  657.,  658.,  659.,  660.,  661.,  662.,  663.,  664.,
        665.,  666.,  667.,  668.,  669.,  670.,  671.,  672.,  673.,
        674.,  675.,  676.,  677.,  678.,  679.,  680.,  681.,  682.,
        683.,  684.,  685.,  686.,  687.,  688.,  689.,  690.,  691.,
        692.,  693.,  694.,  695.,  696.,  697.,  698.,  699.,  700.,
        701.,  702.,  703.,  704.,  705.,  706.,  707.,  708.,  709.,
        710.,  711.,  712.,  713.,  714.,  715.,  716.,  717.,  718.,
        719.,  720.,  721.,  722.,  723.,  724.,  725.,  726.,  727.,
        728.,  729.,  730.,  731.,  732.,  733.,  734.,  735.,  736.,
        737.,  738.,  739.,  740.,  741.,  742.,  743.,  744.,  745.,
        746.,  747.,  748.,  749.,  750.,  751.,  752.,  753.,  754.,
        755.,  756.,  757.,  758.,  759.,  760.,  761.,  762.,  763.,
        764.,  765.,  766.,  767.,  768.,  769.,  770.,  771.,  772.,
        773.,  774.,  775.,  776.,  777.,  778.,  779.,  780.,  781.,
        782.,  783.,  784.,  785.,  786.,  787.,  788.,  789.,  790.,
        791.,  792.,  793.,  794.,  795.,  796.,  797.,  798.,  799.,
        800.,  801.,  802.,  803.,  804.,  805.,  806.,  807.,  808.,
        809.,  810.,  811.,  812.,  813.,  814.,  815.,  816.,  817.,
        818.,  819.,  820.,  821.,  822.,  823.,  824.,  825.,  826.,
        827.,  828.,  829.,  830.,  831.,  832.,  833.,  834.,  835.,
        836.,  837.,  838.,  839.,  840.,  841.,  842.,  843.,  844.,
        845.,  846.,  847.,  848.,  849.,  850.,  851.,  852.,  853.,
        854.,  855.,  856.,  857.,  858.,  859.,  860.,  861.,  862.,
        863.,  864.,  865.,  866.,  867.,  868.,  869.,  870.,  871.,
        872.,  873.,  874.,  875.,  876.,  877.,  878.,  879.,  880.,
        881.,  882.,  883.,  884.,  885.,  886.,  887.,  888.,  889.,
        890.,  891.,  892.,  893.,  894.,  895.,  896.,  897.,  898.,
        899.,  900.,  901.,  902.,  903.,  904.,  905.,  906.,  907.,
        908.,  909.,  910.,  911.,  912.,  913.,  914.,  915.,  916.,
        917.,  918.,  919.,  920.,  921.,  922.,  923.,  924.,  925.,
        926.,  927.,  928.,  929.,  930.,  931.,  932.,  933.,  934.,
        935.,  936.,  937.,  938.,  939.,  940.,  941.,  942.,  943.,
        944.,  945.,  946.,  947.,  948.,  949.,  950.,  951.,  952.,
        953.,  954.,  955.,  956.,  957.,  958.,  959.,  960.,  961.,
        962.,  963.,  964.,  965.,  966.,  967.,  968.,  969.,  970.,
        971.,  972.,  973.,  974.,  975.,  976.,  977.,  978.,  979.,
        980.,  981.,  982.,  983.,  984.,  985.,  986.,  987.,  988.,
        989.,  990.,  991.,  992.,  993.,  994.,  995.,  996.,  997.,
        998.,  999., 1000.,   nan])

In [197]:
messy_data['Quantity'] = messy_data['Quantity'].fillna(messy_data['Quantity'].median())

In [198]:
messy_data['Quantity'].sort_values().unique()

array([ -10.,   -9.,   -8.,   -7.,   -6.,   -5.,   -4.,   -3.,   -2.,
         -1.,    1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,
          9.,   10.,  100.,  101.,  102.,  103.,  104.,  105.,  106.,
        107.,  108.,  109.,  110.,  111.,  112.,  113.,  114.,  115.,
        116.,  117.,  118.,  119.,  120.,  121.,  122.,  123.,  124.,
        125.,  126.,  127.,  128.,  129.,  130.,  131.,  132.,  133.,
        134.,  135.,  136.,  137.,  138.,  139.,  140.,  141.,  142.,
        143.,  144.,  145.,  146.,  147.,  148.,  149.,  150.,  151.,
        152.,  153.,  154.,  155.,  156.,  157.,  158.,  159.,  160.,
        161.,  162.,  163.,  164.,  165.,  166.,  167.,  168.,  169.,
        170.,  171.,  172.,  173.,  174.,  175.,  176.,  177.,  178.,
        179.,  180.,  181.,  182.,  183.,  184.,  185.,  186.,  187.,
        188.,  189.,  190.,  191.,  192.,  193.,  194.,  195.,  196.,
        197.,  198.,  199.,  200.,  201.,  202.,  203.,  204.,  205.,
        206.,  207.,  208.,  209.,  210.,  211.,  212.,  213.,  214.,
        215.,  216.,  217.,  218.,  219.,  220.,  221.,  222.,  223.,
        224.,  225.,  226.,  227.,  228.,  229.,  230.,  231.,  232.,
        233.,  234.,  235.,  236.,  237.,  238.,  239.,  240.,  241.,
        242.,  243.,  244.,  245.,  246.,  247.,  248.,  249.,  250.,
        251.,  252.,  253.,  254.,  255.,  256.,  257.,  258.,  259.,
        260.,  261.,  262.,  263.,  264.,  265.,  266.,  267.,  268.,
        269.,  270.,  271.,  272.,  273.,  274.,  275.,  276.,  277.,
        278.,  279.,  280.,  281.,  282.,  283.,  284.,  285.,  286.,
        287.,  288.,  289.,  290.,  291.,  292.,  293.,  294.,  295.,
        296.,  297.,  298.,  299.,  300.,  301.,  302.,  303.,  304.,
        305.,  306.,  307.,  308.,  309.,  310.,  311.,  312.,  313.,
        314.,  315.,  316.,  317.,  318.,  319.,  320.,  321.,  322.,
        323.,  324.,  325.,  326.,  327.,  328.,  329.,  330.,  331.,
        332.,  333.,  334.,  335.,  336.,  337.,  338.,  339.,  340.,
        341.,  342.,  343.,  344.,  345.,  346.,  347.,  348.,  349.,
        350.,  351.,  352.,  353.,  354.,  355.,  356.,  357.,  358.,
        359.,  360.,  361.,  362.,  363.,  364.,  365.,  366.,  367.,
        368.,  369.,  370.,  371.,  372.,  373.,  374.,  375.,  376.,
        377.,  378.,  379.,  380.,  381.,  382.,  383.,  384.,  385.,
        386.,  387.,  388.,  389.,  390.,  391.,  392.,  393.,  394.,
        395.,  396.,  397.,  398.,  399.,  400.,  401.,  402.,  403.,
        404.,  405.,  406.,  407.,  408.,  409.,  410.,  411.,  412.,
        413.,  414.,  415.,  416.,  417.,  418.,  419.,  420.,  421.,
        422.,  423.,  424.,  425.,  426.,  427.,  428.,  429.,  430.,
        431.,  432.,  433.,  434.,  435.,  436.,  437.,  438.,  439.,
        440.,  441.,  442.,  443.,  444.,  445.,  446.,  447.,  448.,
        449.,  450.,  451.,  452.,  453.,  454.,  455.,  456.,  457.,
        458.,  459.,  460.,  461.,  462.,  463.,  464.,  465.,  466.,
        467.,  468.,  469.,  470.,  471.,  472.,  473.,  474.,  475.,
        476.,  477.,  478.,  479.,  480.,  481.,  482.,  483.,  484.,
        485.,  486.,  487.,  488.,  489.,  490.,  491.,  492.,  493.,
        494.,  495.,  496.,  497.,  498.,  499.,  500.,  501.,  502.,
        503.,  504.,  505.,  506.,  507.,  508.,  509.,  510.,  511.,
        512.,  513.,  514.,  515.,  516.,  517.,  518.,  519.,  520.,
        521.,  522.,  523.,  524.,  525.,  526.,  527.,  528.,  529.,
        530.,  531.,  532.,  533.,  534.,  535.,  536.,  537.,  538.,
        539.,  540.,  541.,  542.,  543.,  544.,  545.,  546.,  547.,
        548.,  549.,  550.,  551.,  552.,  553.,  554.,  555.,  556.,
        557.,  558.,  559.,  560.,  561.,  562.,  563.,  564.,  565.,
        566.,  567.,  568.,  569.,  570.,  571.,  572.,  573.,  574.,
        575.,  576.,  577.,  578.,  579.,  580.,  581.,  582.,  583.,
        584.,  585.,  586.,  587.,  588.,  589.,  590.,  591.,  592.,
        593.,  594.,  595.,  596.,  597.,  598.,  599.,  600.,  601.,
        602.,  603.,  604.,  605.,  606.,  607.,  608.,  609.,  610.,
        611.,  612.,  613.,  614.,  615.,  616.,  617.,  618.,  619.,
        620.,  621.,  622.,  623.,  624.,  625.,  626.,  627.,  628.,
        629.,  630.,  631.,  632.,  633.,  634.,  635.,  636.,  637.,
        638.,  639.,  640.,  641.,  642.,  643.,  644.,  645.,  646.,
        647.,  648.,  649.,  650.,  651.,  652.,  653.,  654.,  655.,
        656.,  657.,  658.,  659.,  660.,  661.,  662.,  663.,  664.,
        665.,  666.,  667.,  668.,  669.,  670.,  671.,  672.,  673.,
        674.,  675.,  676.,  677.,  678.,  679.,  680.,  681.,  682.,
        683.,  684.,  685.,  686.,  687.,  688.,  689.,  690.,  691.,
        692.,  693.,  694.,  695.,  696.,  697.,  698.,  699.,  700.,
        701.,  702.,  703.,  704.,  705.,  706.,  707.,  708.,  709.,
        710.,  711.,  712.,  713.,  714.,  715.,  716.,  717.,  718.,
        719.,  720.,  721.,  722.,  723.,  724.,  725.,  726.,  727.,
        728.,  729.,  730.,  731.,  732.,  733.,  734.,  735.,  736.,
        737.,  738.,  739.,  740.,  741.,  742.,  743.,  744.,  745.,
        746.,  747.,  748.,  749.,  750.,  751.,  752.,  753.,  754.,
        755.,  756.,  757.,  758.,  759.,  760.,  761.,  762.,  763.,
        764.,  765.,  766.,  767.,  768.,  769.,  770.,  771.,  772.,
        773.,  774.,  775.,  776.,  777.,  778.,  779.,  780.,  781.,
        782.,  783.,  784.,  785.,  786.,  787.,  788.,  789.,  790.,
        791.,  792.,  793.,  794.,  795.,  796.,  797.,  798.,  799.,
        800.,  801.,  802.,  803.,  804.,  805.,  806.,  807.,  808.,
        809.,  810.,  811.,  812.,  813.,  814.,  815.,  816.,  817.,
        818.,  819.,  820.,  821.,  822.,  823.,  824.,  825.,  826.,
        827.,  828.,  829.,  830.,  831.,  832.,  833.,  834.,  835.,
        836.,  837.,  838.,  839.,  840.,  841.,  842.,  843.,  844.,
        845.,  846.,  847.,  848.,  849.,  850.,  851.,  852.,  853.,
        854.,  855.,  856.,  857.,  858.,  859.,  860.,  861.,  862.,
        863.,  864.,  865.,  866.,  867.,  868.,  869.,  870.,  871.,
        872.,  873.,  874.,  875.,  876.,  877.,  878.,  879.,  880.,
        881.,  882.,  883.,  884.,  885.,  886.,  887.,  888.,  889.,
        890.,  891.,  892.,  893.,  894.,  895.,  896.,  897.,  898.,
        899.,  900.,  901.,  902.,  903.,  904.,  905.,  906.,  907.,
        908.,  909.,  910.,  911.,  912.,  913.,  914.,  915.,  916.,
        917.,  918.,  919.,  920.,  921.,  922.,  923.,  924.,  925.,
        926.,  927.,  928.,  929.,  930.,  931.,  932.,  933.,  934.,
        935.,  936.,  937.,  938.,  939.,  940.,  941.,  942.,  943.,
        944.,  945.,  946.,  947.,  948.,  949.,  950.,  951.,  952.,
        953.,  954.,  955.,  956.,  957.,  958.,  959.,  960.,  961.,
        962.,  963.,  964.,  965.,  966.,  967.,  968.,  969.,  970.,
        971.,  972.,  973.,  974.,  975.,  976.,  977.,  978.,  979.,
        980.,  981.,  982.,  983.,  984.,  985.,  986.,  987.,  988.,
        989.,  990.,  991.,  992.,  993.,  994.,  995.,  996.,  997.,
        998.,  999., 1000.])

In [199]:
messy_data['Quantity'] = messy_data['Quantity'].astype(int)

In [200]:
messy_data['Quantity'] = messy_data['Quantity'].apply(lambda x: x if x >= 0 else 0 )

In [201]:
messy_data['Quantity'].sort_values().unique()

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  151,  152,  153,  154,
        155,  156,  157,  158,  159,  160,  161,  162,  163,  164,  165,
        166,  167,  168,  169,  170,  171,  172,  173,  174,  175,  176,
        177,  178,  179,  180,  181,  182,  183,  184,  185,  186,  187,
        188,  189,  190,  191,  192,  193,  194,  195,  196,  197,  198,
        199,  200,  201,  202,  203,  204,  205,  206,  207,  208,  209,
        210,  211,  212,  213,  214,  215,  216,  217,  218,  219,  220,
        221,  222,  223,  224,  225,  226,  227,  228,  229,  230,  231,
        232,  233,  234,  235,  236,  237,  238,  239,  240,  241,  242,
        243,  244,  245,  246,  247,  248,  249,  250,  251,  252,  253,
        254,  255,  256,  257,  258,  259,  260,  261,  262,  263,  264,
        265,  266,  267,  268,  269,  270,  271,  272,  273,  274,  275,
        276,  277,  278,  279,  280,  281,  282,  283,  284,  285,  286,
        287,  288,  289,  290,  291,  292,  293,  294,  295,  296,  297,
        298,  299,  300,  301,  302,  303,  304,  305,  306,  307,  308,
        309,  310,  311,  312,  313,  314,  315,  316,  317,  318,  319,
        320,  321,  322,  323,  324,  325,  326,  327,  328,  329,  330,
        331,  332,  333,  334,  335,  336,  337,  338,  339,  340,  341,
        342,  343,  344,  345,  346,  347,  348,  349,  350,  351,  352,
        353,  354,  355,  356,  357,  358,  359,  360,  361,  362,  363,
        364,  365,  366,  367,  368,  369,  370,  371,  372,  373,  374,
        375,  376,  377,  378,  379,  380,  381,  382,  383,  384,  385,
        386,  387,  388,  389,  390,  391,  392,  393,  394,  395,  396,
        397,  398,  399,  400,  401,  402,  403,  404,  405,  406,  407,
        408,  409,  410,  411,  412,  413,  414,  415,  416,  417,  418,
        419,  420,  421,  422,  423,  424,  425,  426,  427,  428,  429,
        430,  431,  432,  433,  434,  435,  436,  437,  438,  439,  440,
        441,  442,  443,  444,  445,  446,  447,  448,  449,  450,  451,
        452,  453,  454,  455,  456,  457,  458,  459,  460,  461,  462,
        463,  464,  465,  466,  467,  468,  469,  470,  471,  472,  473,
        474,  475,  476,  477,  478,  479,  480,  481,  482,  483,  484,
        485,  486,  487,  488,  489,  490,  491,  492,  493,  494,  495,
        496,  497,  498,  499,  500,  501,  502,  503,  504,  505,  506,
        507,  508,  509,  510,  511,  512,  513,  514,  515,  516,  517,
        518,  519,  520,  521,  522,  523,  524,  525,  526,  527,  528,
        529,  530,  531,  532,  533,  534,  535,  536,  537,  538,  539,
        540,  541,  542,  543,  544,  545,  546,  547,  548,  549,  550,
        551,  552,  553,  554,  555,  556,  557,  558,  559,  560,  561,
        562,  563,  564,  565,  566,  567,  568,  569,  570,  571,  572,
        573,  574,  575,  576,  577,  578,  579,  580,  581,  582,  583,
        584,  585,  586,  587,  588,  589,  590,  591,  592,  593,  594,
        595,  596,  597,  598,  599,  600,  601,  602,  603,  604,  605,
        606,  607,  608,  609,  610,  611,  612,  613,  614,  615,  616,
        617,  618,  619,  620,  621,  622,  623,  624,  625,  626,  627,
        628,  629,  630,  631,  632,  633,  634,  635,  636,  637,  638,
        639,  640,  641,  642,  643,  644,  645,  646,  647,  648,  649,
        650,  651,  652,  653,  654,  655,  656,  657,  658,  659,  660,
        661,  662,  663,  664,  665,  666,  667,  668,  669,  670,  671,
        672,  673,  674,  675,  676,  677,  678,  679,  680,  681,  682,
        683,  684,  685,  686,  687,  688,  689,  690,  691,  692,  693,
        694,  695,  696,  697,  698,  699,  700,  701,  702,  703,  704,
        705,  706,  707,  708,  709,  710,  711,  712,  713,  714,  715,
        716,  717,  718,  719,  720,  721,  722,  723,  724,  725,  726,
        727,  728,  729,  730,  731,  732,  733,  734,  735,  736,  737,
        738,  739,  740,  741,  742,  743,  744,  745,  746,  747,  748,
        749,  750,  751,  752,  753,  754,  755,  756,  757,  758,  759,
        760,  761,  762,  763,  764,  765,  766,  767,  768,  769,  770,
        771,  772,  773,  774,  775,  776,  777,  778,  779,  780,  781,
        782,  783,  784,  785,  786,  787,  788,  789,  790,  791,  792,
        793,  794,  795,  796,  797,  798,  799,  800,  801,  802,  803,
        804,  805,  806,  807,  808,  809,  810,  811,  812,  813,  814,
        815,  816,  817,  818,  819,  820,  821,  822,  823,  824,  825,
        826,  827,  828,  829,  830,  831,  832,  833,  834,  835,  836,
        837,  838,  839,  840,  841,  842,  843,  844,  845,  846,  847,
        848,  849,  850,  851,  852,  853,  854,  855,  856,  857,  858,
        859,  860,  861,  862,  863,  864,  865,  866,  867,  868,  869,
        870,  871,  872,  873,  874,  875,  876,  877,  878,  879,  880,
        881,  882,  883,  884,  885,  886,  887,  888,  889,  890,  891,
        892,  893,  894,  895,  896,  897,  898,  899,  900,  901,  902,
        903,  904,  905,  906,  907,  908,  909,  910,  911,  912,  913,
        914,  915,  916,  917,  918,  919,  920,  921,  922,  923,  924,
        925,  926,  927,  928,  929,  930,  931,  932,  933,  934,  935,
        936,  937,  938,  939,  940,  941,  942,  943,  944,  945,  946,
        947,  948,  949,  950,  951,  952,  953,  954,  955,  956,  957,
        958,  959,  960,  961,  962,  963,  964,  965,  966,  967,  968,
        969,  970,  971,  972,  973,  974,  975,  976,  977,  978,  979,
        980,  981,  982,  983,  984,  985,  986,  987,  988,  989,  990,
        991,  992,  993,  994,  995,  996,  997,  998,  999, 1000])

Now Working with Column Name

In [202]:
messy_data['Transaction_Status'] = messy_data['Transaction_Status'].fillna('completed')

In [203]:
messy_data['Transaction_Status'].unique()

array(['completed', 'Pending', 'Completed', 'complete', 'Failed'],
      dtype=object)

In [204]:
messy_data['Transaction_Status'] = messy_data['Transaction_Status'].replace({'completed': 'Completed',
                                                                            'complete': 'Completed'})

In [205]:
messy_data['Transaction_Status'].unique()

array(['Completed', 'Pending', 'Failed'], dtype=object)

In [206]:
messy_data['Payment_Method'].unique()

array(['pay pal', 'creditcard', 'credit card', 'PayPal', 'Cash',
       'PayPal ', 'Credit Card'], dtype=object)

In [207]:
messy_data['Payment_Method'] = messy_data['Payment_Method'].replace({'pay pal': 'Paypal', 'PayPal ': 'Paypal',
                                                                    'creditcard': 'CreditCard', 'credit card': 'CreditCard' })

In [208]:
messy_data['Payment_Method'] = messy_data['Payment_Method'].replace({'Paypal': 'PayPal'})

In [209]:
messy_data['Payment_Method'] = messy_data['Payment_Method'].replace({'Credit Card': 'CreditCard'})

In [210]:
messy_data['Payment_Method'].unique()

array(['PayPal', 'CreditCard', 'Cash'], dtype=object)

In [211]:
messy_data['Product_Name'].unique()

array(['Headphones', 'Coffee ', 'Tablet', 'Tab', 'Coffee Machine',
       'Smartphone', 'Laptop', 'Coffee Ma', 'Cof', 'Smar', 'Coffee M',
       'T', 'Smartp', 'Headp', 'Smart', 'La', 'Lapt', 'Tabl', 'L', 'C',
       'Smartph', 'Hea', 'Head', 'Smartpho', 'Lapto', 'Headphon', 'Table',
       'Headphone', 'Coffee Mac', 'Sm', 'Coffee', 'Headph', 'S',
       'Coffee Mach', 'Smartphon', 'Headpho', 'Coffee Machin', 'Coff',
       'Co', 'Lap', 'H', 'He', 'Ta', 'Coffee Machi', 'Coffe', 'Sma'],
      dtype=object)

In [212]:
messy_data['Product_Name'] = messy_data['Product_Name'].str.lower()

In [213]:
messy_data['Product_Name'] = messy_data['Product_Name'].apply(lambda x: 'coffee' if x.startswith('c') else
                                                             'headphones' if x.startswith('h') else 
                                                              'laptop' if x.startswith('l') else
                                                              'smartphone' if x.startswith('s') else
                                                              'other')

In [214]:
messy_data['Product_Name'].unique()

array(['headphones', 'coffee', 'other', 'smartphone', 'laptop'],
      dtype=object)

In [221]:
messy_data['Transaction_Date'] = pd.to_datetime(messy_data['Transaction_Date'], errors='coerce')

In [224]:
messy_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 94176 entries, 0 to 99998
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      94176 non-null  object
 1   Transaction_Date    29922 non-null  datetime64[ns]
 2   Customer_ID         94176 non-null  object
 3   Product_Name        94176 non-null  object
 4   Quantity            94176 non-null  int64
 5   Price               94176 non-null  float64
 6   Payment_Method      94176 non-null  object
 7   Transaction_Status  94176 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 6.5+ MB

So This is clean Data and we don't do anything with Transactions Date because we don't know anything about it

In [222]:
clean_data = messy_data

In [223]:
clean_data

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status
0,T00001,2024-08-02,C2205,headphones,0,420.210000,PayPal,Completed
1,T00002,2020-02-10,C3156,coffee,469,-445.342025,CreditCard,Pending
2,T00003,NaT,C2919,other,0,810.993012,CreditCard,Completed
3,T00004,2020-08-17,C3009,other,0,868.608341,PayPal,Pending
4,T00005,NaT,C3488,coffee,0,-763.122449,PayPal,Completed
...,...,...,...,...,...,...,...,...
99994,T94172,NaT,C2153,smartphone,741,52.005263,PayPal,Completed
99995,T94173,2021-10-06,C1743,headphones,0,240.003238,PayPal,Completed
99996,T94174,2024-08-25,C4830,smartphone,6,503.829517,CreditCard,Completed
99997,T94175,NaT,C280,laptop,0,52.005263,PayPal,Completed
99998,T94176,2020-07-12,C4059,headphones,10,52.005263,PayPal,Completed